import Foundation

public struct DockCatDiagnosticSnapshot: Codable, Equatable, Sendable {
    public static let currentSchemaVersion = 1
    public let schemaVersion: Int
    public let generatedAt: Date
    public let consistency: DiagnosticConsistencyInfo
    public let application: DiagnosticApplicationInfo
    public let runtime: DiagnosticRuntimeInfo
    public let sources: DiagnosticSourceInfo
    public let queue: DiagnosticQueueInfo
    public let presentation: DiagnosticPresentationInfo
    public let placement: DiagnosticPlacementInfo?
    public let accessibility: DiagnosticAccessibilityInfo
    public let recentEvents: [DockCatDiagnosticEvent]
    public init(schemaVersion: Int = Self.currentSchemaVersion, generatedAt: Date, consistency: DiagnosticConsistencyInfo, application: DiagnosticApplicationInfo, runtime: DiagnosticRuntimeInfo, sources: DiagnosticSourceInfo, queue: DiagnosticQueueInfo, presentation: DiagnosticPresentationInfo, placement: DiagnosticPlacementInfo?, accessibility: DiagnosticAccessibilityInfo, recentEvents: [DockCatDiagnosticEvent]) {
        self.schemaVersion = schemaVersion; self.generatedAt = generatedAt; self.consistency = consistency; self.application = application; self.runtime = runtime; self.sources = sources; self.queue = queue; self.presentation = presentation; self.placement = placement; self.accessibility = accessibility; self.recentEvents = recentEvents
    }
}
public struct DiagnosticConsistencyInfo: Codable, Equatable, Sendable { public let queueRevisionStable: Bool; public let initialQueueRevision: UInt64; public let finalQueueRevision: UInt64; public init(queueRevisionStable: Bool, initialQueueRevision: UInt64, finalQueueRevision: UInt64) { self.queueRevisionStable = queueRevisionStable; self.initialQueueRevision = initialQueueRevision; self.finalQueueRevision = finalQueueRevision } }
public struct DiagnosticApplicationInfo: Codable, Equatable, Sendable { public let productName, bundleIdentifier, marketingVersion, buildNumber, macOSVersion, processArchitecture, buildConfiguration: String; public init(productName: String, bundleIdentifier: String, marketingVersion: String, buildNumber: String, macOSVersion: String, processArchitecture: String, buildConfiguration: String) { self.productName=productName; self.bundleIdentifier=bundleIdentifier; self.marketingVersion=marketingVersion; self.buildNumber=buildNumber; self.macOSVersion=macOSVersion; self.processArchitecture=processArchitecture; self.buildConfiguration=buildConfiguration } }
public struct DiagnosticRuntimeInfo: Codable, Equatable, Sendable { public let lifecycleMode, catState, effectiveVisualMode: String; public let deliveryPaused, transitioning, recovering: Bool; public let runtimeGeneration, currentQueueRevision: UInt64; public init(lifecycleMode: String, catState: String, effectiveVisualMode: String, deliveryPaused: Bool, transitioning: Bool, recovering: Bool, runtimeGeneration: UInt64, currentQueueRevision: UInt64) { self.lifecycleMode=lifecycleMode; self.catState=catState; self.effectiveVisualMode=effectiveVisualMode; self.deliveryPaused=deliveryPaused; self.transitioning=transitioning; self.recovering=recovering; self.runtimeGeneration=runtimeGeneration; self.currentQueueRevision=currentQueueRevision } }
public struct DiagnosticSourceInfo: Codable, Equatable, Sendable { public let internalTestAvailable, urlSourceAvailable, systemSourceRequested: Bool; public let systemSourceHealth: String; public let systemSourceReason: String?; public let nativeBannerCloseRequested: Bool; public let exclusionBundleIdentifierCount: Int; public init(internalTestAvailable: Bool, urlSourceAvailable: Bool, systemSourceRequested: Bool, systemSourceHealth: String, systemSourceReason: String?, nativeBannerCloseRequested: Bool, exclusionBundleIdentifierCount: Int) { self.internalTestAvailable=internalTestAvailable; self.urlSourceAvailable=urlSourceAvailable; self.systemSourceRequested=systemSourceRequested; self.systemSourceHealth=systemSourceHealth; self.systemSourceReason=systemSourceReason; self.nativeBannerCloseRequested=nativeBannerCloseRequested; self.exclusionBundleIdentifierCount=exclusionBundleIdentifierCount } }
public struct DiagnosticQueueInfo: Codable, Equatable, Sendable { public let currentExists: Bool; public let pendingCount, queueLimit, recentCompletionCount, recentCompletionCapacity: Int; public let paused: Bool; public init(currentExists: Bool, pendingCount: Int, queueLimit: Int, paused: Bool, recentCompletionCount: Int, recentCompletionCapacity: Int) { self.currentExists=currentExists; self.pendingCount=pendingCount; self.queueLimit=queueLimit; self.paused=paused; self.recentCompletionCount=recentCompletionCount; self.recentCompletionCapacity=recentCompletionCapacity } }
public struct DiagnosticPresentationInfo: Codable, Equatable, Sendable { public let sessionExists: Bool; public let sessionGeneration: UInt64?; public let phase: String?; public let contentRevision: UInt64?; public let classification: String?; public let remainingTransientDurationSeconds: Int?; public let dismissalCause, cancellationReason: String?; public init(sessionExists: Bool, sessionGeneration: UInt64?, phase: String?, contentRevision: UInt64?, classification: String?, remainingTransientDurationSeconds: Int?, dismissalCause: String?, cancellationReason: String?) { self.sessionExists=sessionExists; self.sessionGeneration=sessionGeneration; self.phase=phase; self.contentRevision=contentRevision; self.classification=classification; self.remainingTransientDurationSeconds=remainingTransientDurationSeconds; self.dismissalCause=dismissalCause; self.cancellationReason=cancellationReason } }
public struct DiagnosticRect: Codable, Equatable, Sendable { public let x,y,width,height: Double; public init(x: Double, y: Double, width: Double, height: Double) { self.x=x; self.y=y; self.width=width; self.height=height } }
public struct DiagnosticPlacementInfo: Codable, Equatable, Sendable { public let dockEdge, geometryConfidence: String; public let screenFrame, visibleFrame: DiagnosticRect; public let requestedDisplayAvailable, fallbackUsed, calibrationPresent: Bool; public let displayToken: String; public init(dockEdge: String, geometryConfidence: String, screenFrame: DiagnosticRect, visibleFrame: DiagnosticRect, requestedDisplayAvailable: Bool, fallbackUsed: Bool, calibrationPresent: Bool, displayToken: String) { self.dockEdge=dockEdge; self.geometryConfidence=geometryConfidence; self.screenFrame=screenFrame; self.visibleFrame=visibleFrame; self.requestedDisplayAvailable=requestedDisplayAvailable; self.fallbackUsed=fallbackUsed; self.calibrationPresent=calibrationPresent; self.displayToken=displayToken } }
public struct DiagnosticAccessibilityInfo: Codable, Equatable, Sendable { public let reduceMotion, increasedContrast, reduceTransparency, differentiateWithoutColor, accessibilityTrusted: Bool; public init(reduceMotion: Bool, increasedContrast: Bool, reduceTransparency: Bool, differentiateWithoutColor: Bool, accessibilityTrusted: Bool) { self.reduceMotion=reduceMotion; self.increasedContrast=increasedContrast; self.reduceTransparency=reduceTransparency; self.differentiateWithoutColor=differentiateWithoutColor; self.accessibilityTrusted=accessibilityTrusted } }
